config/routes.rb
Jcrm::Application.routes.draw do

  root to: "home#show"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  get "/search", to: "search#search"
  get "/search_link", to: "search#search_link"

  resources :accounts do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :contacts do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :opportunities do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :quotes

  resources :notes do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :users do
    member do
      post "link"
      post "unlink"
    end
  end

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  has_many :note_accounts
  has_many :accounts, through: :note_accounts
  has_many :note_contacts
  has_many :contacts, through: :note_contacts
  has_many :note_opportunities
  has_many :opportunities, through: :note_opportunities

  before_save :generate_searchable

  validates :user_id, presence: true
  validates :title, presence: true
  validates :body, presence: true

  private

  def generate_searchable
    self.search_display_name = self.title
    self.search_key = self.title.gsub(/[^0-9a-z]/i, '').downcase
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_user
  before_action :require_admin, only: [:unlink]

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = session[:user_id]

    if @note.save
      flash[:notice] = "Note successfully created!"
      redirect_to note_path(@note)
    else
      render :new
    end
  end

  def show
    @record_type = Note
    @record_id = params[:id]
    @note = Note.find(params[:id])
    @tab = params[:tab]
    @accounts = @note.accounts
    @contacts = @note.contacts
    @opportunities = @note.opportunities
    @user = current_user
  end

  def update
    @note = Note.find(params[:id])

    if @note.update(note_params)
      flash[:notice] = "Note successfully updated!"
      redirect_to note_path(@note)
    else
      render :new
    end
  end

  def link
    @note = Note.find(params[:id])
    @current_record = params[:record_type].constantize.find(params[:record_id])

    if @current_record.notes.include?(@note)
      flash[:danger] = "'#{@current_record.search_display_name}' is already linked to '#{@note.search_display_name}'"
      redirect_to @current_record
    else
      @current_record.notes << @note
      flash[:notice] = "'#{@current_record.search_display_name}' successfully linked to '#{@note.search_display_name}'"
      redirect_to @current_record
    end
  end

  def unlink
    @note = Note.find(params[:id])
    @current_record = params[:record_type].constantize.find(params[:record_id])
    @current_record.notes.delete(@note)
    flash[:notice] = "'#{@note.search_display_name}' successfully unlinked from '#{@current_record.search_display_name}'"
    redirect_to @current_record
  end

  private

  def note_params
    params.require(:note).permit!
  end

end

app/views/notes/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= record_heading %></h3>
  </div>
  <div class="panel-body">
    <%= form_for @note do |f| %>
      <div class="row">
        <div class="form-group col-xs-6">
          <%= f.label :title, "Title" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <% if ! @note.new_record? %>
          <div class="form-group col-xs-3" id="disabledInput">
            <%= f.label :created_at, "Created" %>
            <%= f.text_field :created_at, class: "form-control", disabled: true %>
          </div>
          <div class="form-group col-xs-3">
            <%= f.label :updated_at, "Last Updated" %>
            <%= f.text_field :updated_at, class: "form-control", disabled: true %>
          </div>
        <% end %>
      </div>
      <div class="row">
        <div class="form-group col-xs-12">
          <%= f.label :body, "Text" %>
          <%= f.text_area :body, class: "form-control", rows: "12" %>
        </div>
      </div>
      <hr/>
      <%= f.submit @note.new_record? ? "Create Note" : "Update Note", class: "btn btn-primary pull-right" %>
    <% end %>
  </div>
</div>

app/views/notes/_short_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= note.search_display_name %></h3>
  </div>
  <div class="panel-body">
    <%= form_for note do |f| %>
      <div class="row">
        <div class="form-group col-xs-6">
          <%= f.label :title, "Title" %>
          <%= f.text_field :title, class: "form-control", disabled: true %>
        </div>
        <div class="form-group col-xs-3" id="disabledInput">
          <%= f.label :created_at, "Created" %>
          <%= f.text_field :created_at, class: "form-control", disabled: true %>
        </div>
        <div class="form-group col-xs-3">
          <%= f.label :updated_at, "Last Updated" %>
          <%= f.text_field :updated_at, class: "form-control", disabled: true %>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-xs-12">
          <%= f.label :body, "Text" %>
          <%= f.text_area :body, class: "form-control", rows: "12", disabled: true %>
        </div>
      </div>
    <% end %>
    <hr/>
    <% if current_user.is_admin? %>
      <%= link_to "Unlink Note", unlink_note_path(note, record_type: @record_type, record_id: @record_id), method: :post, class: "btn btn-default pull-left" %>
    <% end %>
    <%= link_to "View Note", note_path(note), class: "btn btn-default pull-right" %>
  </div>
</div>

app/views/notes/new.html.erb
<div class="col-xs-8 col-xs-offset-2">
  <%= render "shared/errors", record: @note %>
  <%= render "notes/form", record_heading: "Create New Note" %>
</div>

app/views/notes/show.html.erb
<div class="col-xs-8">
  <%= render "shared/errors", record: @note %>
  <%= render "notes/form", record_heading: "Note: #{@note.search_display_name}" %>
</div>

<div class="col-xs-4">
  <%= render "shared/link_records" %>
</div>

<div class="col-xs-8">
  <ul class="nav nav-pills">
    <li role="presentation" class="<%= 'active' if @tab == 'accounts' || @tab == nil %>">
      <%= link_to "Accounts", note_path(@note, tab: "accounts") %>
    </li>
    <li role="presentation" class="<%= 'active' if @tab == 'contacts' %>">
      <%= link_to "Contacts", note_path(@note, tab: "contacts") %>
    </li>
    <li role="presentation" class="<%= 'active' if @tab == 'opportunities' %>">
      <%= link_to "Opportunities", note_path(@note, tab: "opportunities") %>
    </li>
    <li role="presentation" class="<%= 'active' if @tab == 'user' %>">
      <%= link_to "Note Creator", note_path(@note, tab: "user") %>
    </li>
  </ul>
  <br/>

  <% if params[:tab] == "accounts" || params[:tab] == nil %>
    <% @accounts.each do |account| %>
      <%= render "accounts/short_form", account: account %>
    <% end %>
  <% elsif params[:tab] == "contacts" %>
    <% @contacts.each do |contact| %>
      <%= render "contacts/short_form", contact: contact %>
    <% end %>
  <% elsif params[:tab] == "opportunities" %>
    <% @opportunities.each do |opportunity| %>
      <%= render "opportunities/short_form", opportunity: opportunity %>
    <% end %>
  <% else params[:tab] == "user" %>
    <%= render "users/short_form", user: @user %>
  <% end %>

</div>