config/routes.rb
Jcrm::Application.routes.draw do

  root to: "home#show"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  get "/search", to: "search#search"
  get "/search_link", to: "search#search_link"

  resources :accounts do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :contacts do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :opportunities do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :quotes

  resources :notes do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :users do
    member do
      post "link"
      post "unlink"
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :account_contacts
  has_many :contacts, through: :account_contacts
  has_many :opportunity_accounts
  has_many :opportunities, through: :opportunity_accounts
  has_many :note_accounts
  has_many :notes, through: :note_accounts
  belongs_to :industry

  before_save :generate_searchable

  validates :name, presence: true, uniqueness: true, length: {minimum: 3}
  validates :street, presence: true
  validates :city, presence: true
  validates :region, presence: true
  validates :postal_code, presence: true
  validates :country, presence: true
  validates :industry_id, presence: true
  validates :website, presence: true

  private

  def generate_searchable
    self.search_display_name = self.name
    self.search_key = self.name.gsub(/[^0-9a-z]/i, '').downcase
  end
end

app/models/account_contact.rb
class AccountContact < ActiveRecord::Base
  belongs_to :account
  belongs_to :contact
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :account_contacts
  has_many :accounts, through: :account_contacts
  has_many :opportunity_contacts
  has_many :opportunities, through: :opportunity_contacts
  has_many :note_contacts
  has_many :notes, through: :note_contacts

  before_save :generate_searchable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone_number, length: { is: 10 }, numericality: { only_integer: true }

  private

  def generate_searchable
    self.search_display_name = "#{self.first_name} #{self.last_name}"
    self.search_key = (self.first_name + self.last_name).gsub(/[^0-9a-z]/i, '').downcase
  end
end

app/models/industry.rb
class Industry < ActiveRecord::Base
  has_many :accounts
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  has_many :note_accounts
  has_many :accounts, through: :note_accounts
  has_many :note_contacts
  has_many :contacts, through: :note_contacts
  has_many :note_opportunities
  has_many :opportunities, through: :note_opportunities

  before_save :generate_searchable

  validates :user_id, presence: true
  validates :title, presence: true
  validates :body, presence: true

  private

  def generate_searchable
    self.search_display_name = self.title
    self.search_key = self.title.gsub(/[^0-9a-z]/i, '').downcase
  end
end

app/models/note_account.rb
class NoteAccount < ActiveRecord::Base
  belongs_to :note
  belongs_to :account
end

app/models/note_contact.rb
class NoteContact < ActiveRecord::Base
  belongs_to :note
  belongs_to :contact
end

app/models/note_opportunity.rb
class NoteOpportunity < ActiveRecord::Base
  belongs_to :note
  belongs_to :opportunity
end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  belongs_to :opportunity_stage
  has_many :opportunity_accounts
  has_many :accounts, through: :opportunity_accounts
  has_many :opportunity_contacts
  has_many :contacts, through: :opportunity_contacts
  has_many :quotes
  has_many :note_opportunities
  has_many :notes, through: :note_opportunities
  has_many :opportunity_users
  has_many :users, through: :opportunity_users

  before_save :generate_searchable

  validates :name, presence: true

  private

  def generate_searchable
    self.search_display_name = self.name
    self.search_key = self.name.gsub(/[^0-9a-z]/i, '').downcase
  end
end

app/models/opportunity_account.rb
class OpportunityAccount < ActiveRecord::Base
  belongs_to :opportunity
  belongs_to :account
end

app/models/opportunity_contact.rb
class OpportunityContact < ActiveRecord::Base
  belongs_to :opportunity
  belongs_to :contact
end

app/models/opportunity_stage.rb
class OpportunityStage < ActiveRecord::Base
  has_many :opportunities
end

app/models/opportunity_user.rb
class OpportunityUser < ActiveRecord::Base
  belongs_to :opportunity
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :transactions
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :opportunity
  has_many :transactions

  validates :product_1_qty, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :product_2_qty, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :product_3_qty, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def value
    val_1 = self.product_1_qty * Product.find(1).price
    val_2 = self.product_2_qty * Product.find(2).price
    val_3 = self.product_3_qty * Product.find(3).price
    val_1 + val_2 + val_3
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :quote
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  has_many :opportunity_users
  has_many :opportunities, through: :opportunity_users
  has_many :notes

  before_save :generate_searchable

  has_secure_password validations: false

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true, numericality: {only_integer: true},
    length: { is: 10 }
  validates :password, presence: true, length: { minimum: 8, maximum: 16 }, on: :create
  validates_confirmation_of :password, on: :create

  def is_admin?
    self.role.name == "Admin"
  end

  private

  def generate_searchable
    self.search_display_name = "#{self.first_name} #{self.last_name}"
    self.search_key = (self.first_name + self.last_name).gsub(/[^0-9a-z]/i, '').downcase
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :require_user
  before_action :load_search, only: [:search, :search_link]

  def search
    @record_type = nil
  end

  def search_link
    @record_type = params[:record_type]
    @record_id = params[:record_id]
  end

  private

  def load_search
    @accounts = []
    @contacts = []
    @opportunities = []
    @notes = []
    @users = []
    accounts = Account.all.sort_by { |account| account.search_display_name }
    contacts = Contact.all.sort_by { |contact| contact.search_display_name }
    opportunities = Opportunity.all.sort_by { |opportunity| opportunity.search_display_name }
    notes = Note.all.sort_by { |note| note.created_at }
    users = User.all.sort_by { |user| user.search_display_name }
    query = params[:query].gsub(/[^0-9a-z]/i, '').downcase

    accounts.each do |account|
      if account.search_key =~ /#{query}/
        @accounts << account
      end
    end

    contacts.each do |contact|
      if contact.search_key =~ /#{query}/
        @contacts << contact
      end
    end

    opportunities.each do |opportunity|
      if opportunity.search_key =~ /#{query}/
        @opportunities << opportunity
      end
    end

    notes.each do |note|
      if note.search_key =~ /#{query}/
        @notes << note
      end
    end

    users.each do |user|
      if user.search_key =~ /#{query}/
        @users << user
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/search/search.html.erb
<div class="col-xs-2">
  <h4>Search results ...</h4>
</div>

<div class="col-xs-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Accounts</h3>
      </div>
      <div class="panel-body">
        <% @accounts.each do |account| %>
          <%= link_to account.search_display_name, account_path(account), class: "btn btn-block btn-default" %>
        <% end %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Contacts</h3>
      </div>
      <div class="panel-body">
        <% @contacts.each do |contact| %>
          <%= link_to "#{contact.search_display_name} (#{contact.email})", contact_path(contact), class: "btn btn-block btn-default" %>
        <% end %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Opportunities</h3>
      </div>
      <div class="panel-body">
        <% @opportunities.each do |opportunity| %>
          <%= link_to opportunity.search_display_name, opportunity_path(opportunity), class: "btn btn-block btn-default" %>
        <% end %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Notes</h3>
      </div>
      <div class="panel-body">
        <% @notes.each do |note| %>
          <%= link_to note.search_display_name, note_path(note), class: "btn btn-block btn-default" %>
        <% end %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Users</h3>
      </div>
      <div class="panel-body">
        <% @users.each do |user| %>
          <%= link_to "#{user.search_display_name} (#{user.email})", user_path(user), class: "btn btn-block btn-default" %>
        <% end %>
      </div>
    </div>
</div>

app/views/search/search_link.html.erb
<div class="col-xs-2">
  <h4>Link to ...</h4>
</div>

<div class="col-xs-8">
  <% if @record_type != "Account" && @record_type != "User" %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Accounts</h3>
      </div>
      <div class="panel-body">
        <% @accounts.each do |account| %>
          <%= link_to account.search_display_name, link_account_path(account, record_type: @record_type, record_id: @record_id), method: :post, class: "btn btn-block btn-default" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <% if @record_type != "Contact" && @record_type != "User" %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Contacts</h3>
      </div>
      <div class="panel-body">
        <% @contacts.each do |contact| %>
          <%= link_to "#{contact.search_display_name} (#{contact.email})", link_contact_path(contact, record_type: @record_type, record_id: @record_id), method: :post, class: "btn btn-block btn-default" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <% if @record_type != "Opportunity" %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Opportunities</h3>
      </div>
      <div class="panel-body">
        <% @opportunities.each do |opportunity| %>
          <%= link_to opportunity.search_display_name, link_opportunity_path(opportunity, record_type: @record_type, record_id: @record_id), method: :post, class: "btn btn-block btn-default" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <% if @record_type != "Note" && @record_type != "User" %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Notes</h3>
      </div>
      <div class="panel-body">
        <% @notes.each do |note| %>
          <%= link_to note.search_display_name, link_note_path(note, record_type: @record_type, record_id: @record_id), method: :post, class: "btn btn-block btn-default" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <% if @record_type == "Opportunity" || @record_type == nil %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Users</h3>
      </div>
      <div class="panel-body">
        <% @users.each do |user| %>
          <%= link_to "#{user.search_display_name} (#{user.email})", link_user_path(user, record_type: @record_type, record_id: @record_id), method: :post, class: "btn btn-block btn-default" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>