config/routes.rb
Jcrm::Application.routes.draw do

  root to: "home#show"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  get "/search", to: "search#search"
  get "/search_link", to: "search#search_link"

  resources :accounts do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :contacts do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :opportunities do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :quotes

  resources :notes do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :users do
    member do
      post "link"
      post "unlink"
    end
  end

end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  belongs_to :opportunity_stage
  has_many :opportunity_accounts
  has_many :accounts, through: :opportunity_accounts
  has_many :opportunity_contacts
  has_many :contacts, through: :opportunity_contacts
  has_many :quotes
  has_many :note_opportunities
  has_many :notes, through: :note_opportunities
  has_many :opportunity_users
  has_many :users, through: :opportunity_users

  before_save :generate_searchable

  validates :name, presence: true

  private

  def generate_searchable
    self.search_display_name = self.name
    self.search_key = self.name.gsub(/[^0-9a-z]/i, '').downcase
  end
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  before_action :require_user
  before_action :require_same_user_or_admin, only: [:update]
  before_action :require_admin, only: [:unlink]

  def new
    @opportunity = Opportunity.new
  end

  def create
    @opportunity = Opportunity.new(opportunity_params)
    @opportunity.users << current_user

    if @opportunity.save
      flash[:notice] = "Opportunity successfully created!"
      redirect_to opportunity_path(@opportunity)
    else
      render :new
    end
  end

  def show
    @record_type = Opportunity
    @record_id = params[:id]
    @opportunity = Opportunity.find(params[:id])
    @tab = params[:tab]
    @accounts = @opportunity.accounts
    @contacts = @opportunity.contacts
    @notes = @opportunity.notes
    @users = @opportunity.users
    @quotes = @opportunity.quotes
  end

  def update
    @opportunity = Opportunity.find(params[:id])

    if @opportunity.update(opportunity_params)
      flash[:notice] = "Opportunity successfully updated"
      redirect_to opportunity_path(@opportunity)
    else
      render :new
    end
  end

  def link
    @opportunity = Opportunity.find(params[:id])
    @current_record = params[:record_type].constantize.find(params[:record_id])

    if @current_record.opportunities.include?(@opportunity)
      flash[:danger] = "'#{@current_record.search_display_name}' is already linked to '#{@opportunity.search_display_name}'"
      redirect_to @current_record
    else
      @current_record.opportunities << @opportunity
      flash[:notice] = "'#{@current_record.search_display_name}' successfully linked to '#{@opportunity.search_display_name}'"
      redirect_to @current_record
    end
  end

  def unlink
    @opportunity = Opportunity.find(params[:id])
    @current_record = params[:record_type].constantize.find(params[:record_id])
    @current_record.opportunities.delete(@opportunity)
    flash[:notice] = "'#{@opportunity.search_display_name}' successfully unlinked from '#{@current_record.search_display_name}'"
    redirect_to @current_record
  end

  private

  def opportunity_params
    params.require(:opportunity).permit!
  end

  def require_same_user_or_admin
    @opportunity = Opportunity.find(params[:id])

    begin
      flash[:danger] = "You do not have access to that action!"
      redirect_to opportunity_path(@opportunity)
    end unless @opportunity.users.include?(current_user) || current_user.is_admin?
  end
end

app/views/opportunities/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= record_heading %></h3>
  </div>
  <div class="panel-body">
    <%= form_for @opportunity do |f| %>
      <div class="row">
        <div class="form-group col-xs-6">
          <%= f.label :name, "Opportunity Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <% if ! @opportunity.new_record? %>
          <div class="form-group col-xs-3">
            <%= f.label :created_at, "Created" %>
            <%= f.text_field :created_at, class: "form-control", disabled: true %>
          </div>
          <div class="form-group col-xs-3">
            <%= f.label :updated_at, "Last Updated" %>
            <%= f.text_field :updated_at, class: "form-control", disabled: true %>
          </div>
        <% end %>
      </div>
      <div class="row">
        <div class="form-group col-xs-6">
          <%= f.label :stage_id, "Stage" %>
          <%= f.select :stage_id, OpportunityStage.all.collect { |p| [ p.stage, p.id ] }, {}, { class: "form-control" } %>
        </div>
        <div class="form-group col-xs-6">
          <%= label_tag :value, "Quote Value" %>
          <div class="input-group">
            <span class="input-group-addon">$</span>
            <%= text_field_tag :value, "#{opportunity_value(@opportunity)}", class: "form-control text-right", disabled: true %>
            <span class="input-group-addon">.00</span>
          </div>
        </div>
      </div>
      <% if @opportunity.new_record? %>
        <hr/>
        <%= f.submit "Create Opportunity", class: "btn btn-primary pull-right" %>
      <% else %>
        <% if @opportunity.users.include?(current_user) || current_user.is_admin? %>
          <hr/>
          <%= link_to "Add New Quote to Opportunity", new_quote_path(opportunity_id: @opportunity), class: "btn btn-default pull-left" %>
          <%= f.submit @opportunity.new_record? ? "Create Opportunity" : "Update Opportunity", class: "btn btn-primary pull-right" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/opportunities/_short_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= opportunity.search_display_name %></h3>
  </div>
  <div class="panel-body">
    <%= form_for opportunity do |f| %>
      <div class="row">
        <div class="form-group col-xs-6">
          <%= f.label :name, "Opportunity Name" %>
          <%= f.text_field :name, class: "form-control", disabled: true %>
        </div>
        <div class="form-group col-xs-3">
          <%= f.label :created_at, "Created" %>
          <%= f.text_field :created_at, class: "form-control", disabled: true %>
        </div>
        <div class="form-group col-xs-3">
          <%= f.label :updated_at, "Last Updated" %>
          <%= f.text_field :updated_at, class: "form-control", disabled: true %>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-xs-6">
          <%= f.label :stage_id, "Stage" %>
          <%= f.select :stage_id, OpportunityStage.all.collect { |p| [ p.stage, p.id ] }, {}, { class: "form-control", disabled: true } %>
        </div>
        <div class="form-group col-xs-6">
          <%= label_tag :value, "Quote Value" %>
          <div class="input-group">
            <span class="input-group-addon">$</span>
            <%= text_field_tag :value, "#{opportunity_value(opportunity)}", class: "form-control text-right", disabled: true %>
            <span class="input-group-addon">.00</span>
          </div>
        </div>
      </div>
    <% end %>
    <hr/>
    <% if current_user.is_admin? %>
      <%= link_to "Unlink Opportunity", unlink_opportunity_path(opportunity, record_type: @record_type, record_id: @record_id), method: :post, class: "btn btn-default pull-left" %>
    <% end %>
    <%= link_to "View Opportunity", opportunity_path(opportunity), class: "btn btn-default pull-right" %>
  </div>
</div>

app/views/opportunities/new.html.erb
<div class="col-xs-8 col-xs-offset-2">
  <%= render "shared/errors", record: @opportunity %>
  <%= render "opportunities/form", record_heading: "Create New Opportunity" %>
</div>

app/views/opportunities/show.html.erb
<div class="col-xs-8">
  <%= render "shared/errors", record: @opportunity %>
  <%= render "opportunities/form", record_heading: "Opportunity: #{@opportunity.search_display_name}" %>
</div>

<div class="col-xs-4">
  <%= render "shared/link_records" %>
</div>

<div class="col-xs-8">
  <ul class="nav nav-pills">
    <li role="presentation" class="<%= 'active' if @tab == 'quotes' || @tab == nil %>">
      <%= link_to "Quotes", opportunity_path(@opportunity, tab: "quotes") %>
    </li>
    <li role="presentation" class="<%= 'active' if @tab == 'accounts' %>">
      <%= link_to "Accounts", opportunity_path(@opportunity, tab: "accounts") %>
    </li>
    <li role="presentation" class="<%= 'active' if @tab == 'contacts' %>">
      <%= link_to "Contacts", opportunity_path(@opportunity, tab: "contacts") %>
    </li>
    <li role="presentation" class="<%= 'active' if @tab == 'notes' %>">
      <%= link_to "Notes", opportunity_path(@opportunity, tab: "notes") %>
    </li>
    <li role="presentation" class="<%= 'active' if @tab == 'users' %>">
      <%= link_to "Opportunity Owners", opportunity_path(@opportunity, tab: "users") %>
    </li>
  </ul>
  <br/>

  <% if params[:tab] == "quotes" || params[:tab] == nil %>
    <% @quotes.each do |quote| %>
      <%= render "quotes/short_form", quote: quote %>
    <% end %>
  <% elsif params[:tab] == "accounts" %>
    <% @accounts.each do |account| %>
      <%= render "accounts/short_form", account: account %>
    <% end %>
  <% elsif params[:tab] == "contacts" %>
    <% @contacts.each do |contact| %>
      <%= render "contacts/short_form", contact: contact %>
    <% end %>
  <% elsif params[:tab] == "notes" %>
    <% @notes.each do |note| %>
      <%= render "notes/short_form", note: note %>
    <% end %>
  <% else params[:tab] == "users" %>
    <% @users.each do |user| %>
      <%= render "users/short_form", user: user %>
    <% end %>
  <% end %>

</div>