config/routes.rb
Jcrm::Application.routes.draw do

  root to: "home#show"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  get "/search", to: "search#search"
  get "/search_link", to: "search#search_link"

  resources :accounts do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :contacts do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :opportunities do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :quotes

  resources :notes do
    member do
      post "link"
      post "unlink"
    end
  end

  resources :users do
    member do
      post "link"
      post "unlink"
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :account_contacts
  has_many :contacts, through: :account_contacts
  has_many :opportunity_accounts
  has_many :opportunities, through: :opportunity_accounts
  has_many :note_accounts
  has_many :notes, through: :note_accounts
  belongs_to :industry

  before_save :generate_searchable

  validates :name, presence: true, uniqueness: true, length: {minimum: 3}
  validates :street, presence: true
  validates :city, presence: true
  validates :region, presence: true
  validates :postal_code, presence: true
  validates :country, presence: true
  validates :industry_id, presence: true
  validates :website, presence: true

  private

  def generate_searchable
    self.search_display_name = self.name
    self.search_key = self.name.gsub(/[^0-9a-z]/i, '').downcase
  end
end

app/models/account_contact.rb
class AccountContact < ActiveRecord::Base
  belongs_to :account
  belongs_to :contact
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :account_contacts
  has_many :accounts, through: :account_contacts
  has_many :opportunity_contacts
  has_many :opportunities, through: :opportunity_contacts
  has_many :note_contacts
  has_many :notes, through: :note_contacts

  before_save :generate_searchable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone_number, length: { is: 10 }, numericality: { only_integer: true }

  private

  def generate_searchable
    self.search_display_name = "#{self.first_name} #{self.last_name}"
    self.search_key = (self.first_name + self.last_name).gsub(/[^0-9a-z]/i, '').downcase
  end
end

app/models/industry.rb
class Industry < ActiveRecord::Base
  has_many :accounts
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  has_many :note_accounts
  has_many :accounts, through: :note_accounts
  has_many :note_contacts
  has_many :contacts, through: :note_contacts
  has_many :note_opportunities
  has_many :opportunities, through: :note_opportunities

  before_save :generate_searchable

  validates :user_id, presence: true
  validates :title, presence: true
  validates :body, presence: true

  private

  def generate_searchable
    self.search_display_name = self.title
    self.search_key = self.title.gsub(/[^0-9a-z]/i, '').downcase
  end
end

app/models/note_account.rb
class NoteAccount < ActiveRecord::Base
  belongs_to :note
  belongs_to :account
end

app/models/note_contact.rb
class NoteContact < ActiveRecord::Base
  belongs_to :note
  belongs_to :contact
end

app/models/note_opportunity.rb
class NoteOpportunity < ActiveRecord::Base
  belongs_to :note
  belongs_to :opportunity
end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  belongs_to :opportunity_stage
  has_many :opportunity_accounts
  has_many :accounts, through: :opportunity_accounts
  has_many :opportunity_contacts
  has_many :contacts, through: :opportunity_contacts
  has_many :quotes
  has_many :note_opportunities
  has_many :notes, through: :note_opportunities
  has_many :opportunity_users
  has_many :users, through: :opportunity_users

  before_save :generate_searchable

  validates :name, presence: true

  private

  def generate_searchable
    self.search_display_name = self.name
    self.search_key = self.name.gsub(/[^0-9a-z]/i, '').downcase
  end
end

app/models/opportunity_account.rb
class OpportunityAccount < ActiveRecord::Base
  belongs_to :opportunity
  belongs_to :account
end

app/models/opportunity_contact.rb
class OpportunityContact < ActiveRecord::Base
  belongs_to :opportunity
  belongs_to :contact
end

app/models/opportunity_stage.rb
class OpportunityStage < ActiveRecord::Base
  has_many :opportunities
end

app/models/opportunity_user.rb
class OpportunityUser < ActiveRecord::Base
  belongs_to :opportunity
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :transactions
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :opportunity
  has_many :transactions

  validates :product_1_qty, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :product_2_qty, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :product_3_qty, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def value
    val_1 = self.product_1_qty * Product.find(1).price
    val_2 = self.product_2_qty * Product.find(2).price
    val_3 = self.product_3_qty * Product.find(3).price
    val_1 + val_2 + val_3
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :quote
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  has_many :opportunity_users
  has_many :opportunities, through: :opportunity_users
  has_many :notes

  before_save :generate_searchable

  has_secure_password validations: false

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true, numericality: {only_integer: true},
    length: { is: 10 }
  validates :password, presence: true, length: { minimum: 8, maximum: 16 }, on: :create
  validates_confirmation_of :password, on: :create

  def is_admin?
    self.role.name == "Admin"
  end

  private

  def generate_searchable
    self.search_display_name = "#{self.first_name} #{self.last_name}"
    self.search_key = (self.first_name + self.last_name).gsub(/[^0-9a-z]/i, '').downcase
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/_messages.html.erb
<div class="col-xs-12">
  <% flash.each do |type, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-message alert-<%= type == :notice ? "success" : "danger" %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= msg %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<% if logged_in? %>
  <nav class="navbar"></nav>
  <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          <span class="glyphicon glyphicon-home"></span>
        <% end %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <form class="navbar-form navbar-left" method="get" action="/search" role="search">
          <div class="form-group">
            <input type="text" class="form-control" style="width: 300px" name="query" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </form>
        <ul class="nav navbar-nav navbar-left">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
              Create New Record ... <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "New Account", new_account_path %>
              </li>
              <li>
                <%= link_to "New Contact", new_contact_path %>
              </li>
              <li>
                <%= link_to "New Opportunity", new_opportunity_path %>
              </li>
              <li>
                <%= link_to "New Note", new_note_path %>
              </li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
              Signed in as: <strong><%= current_user.first_name %></strong> (<%= current_user.role.name %>) <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "My Profile", user_path(current_user) %>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to "Logout", logout_path %>
              </li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>J/CRM</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-image: url('http://boat-sites.com/wp-content/uploads/2014/04/bg-6-full.jpg'); background-repeat: repeat-y;">
  <header>
    <%= render "layouts/navigation" %>
  </header>
  <div class="container">
    <div class="row">
      <% if !logged_in? %>
        <br/>
      <% end %>
      <% if flash %>
        <%= render "layouts/messages" %>
      <% end %>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if record.errors.any? %>
  <div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><strong>Please fix the following errors:</strong></p>
    <ul>
      <% record.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_link_records.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Actions</h3>
  </div>
  <div class="panel-body">
    <%= render "shared/search" %>
  </div>
</div>

app/views/shared/_search.html.erb
<form class="form-inline method="get" action='/search_link' role="search">
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon">Link to:</div>
      <input type="text" class="form-control" name="query" placeholder="Search">
      <input id='record_type' name='record_type' type="hidden" value='<%= @record_type %>' />
      <input id='record_id' name='record_id' type="hidden" value='<%= @record_id %>' />
    </div>
  </div>
  <button type="submit" class="btn btn-default">
    <span class="glyphicon glyphicon-search"></span>
  </button>
</form>